### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by OtakuFra** [if-ai/ComfyUI-IF_AI_tools#102]
Hi guys, after a fresh reinstall of comfyui i still getting troubles with "IF_AI_Tools, see the logs =>

`
To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AImatrix\Data\Packages\ComfyUI\server.py", line 468, in get_object_info
    out[x] = node_info(x)
  File "D:\AImatrix\Data\Packages\ComfyUI\server.py", line 436, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'D:\\AImatrix\\Data\\Packages\\ComfyUI\\input\\IF_AI\\presets\\agents'`

**Comment by if-ai** [comment]
That's step 3 on the installation guide has to move IF_AI folder from
ComfyUI-IF_AI_tools to the root input folder ComfyUI /input /IF_AI
