### ISSUE TITLE
What is this error? [ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.

### ISSUE THREAD

**Issue by ClothingAI** [if-ai/ComfyUI-IF_AI_tools#113]
What is the problem here:

> FETCH DATA from: D:\AI\AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
> [ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
> Traceback (most recent call last):
>   File "D:\AI\AI\ComfyUI\server.py", line 564, in get_object_info
>     out[x] = node_info(x)
>              ^^^^^^^^^^^^
>   File "D:\AI\AI\ComfyUI\server.py", line 531, in node_info
>     info['input'] = obj_class.INPUT_TYPES()
>                     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\AI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 109, in INPUT_TYPES
>     node = cls()
>            ^^^^^
>   File "D:\AI\AI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
>     self.agent_tools = self.load_agent_tools()
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\AI\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in load_agent_tools
>     for filename in os.listdir(self.agents_dir):
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI\\AI\\ComfyUI\\input\\IF_AI\\presets\\agents'
> 
> Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: D:\AI\AI\ComfyUI
> 
> Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: D:\AI\AI\ComfyUI
> 
> Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: D:\AI\AI\ComfyUI
> 
> Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: D:\AI\AI\ComfyUI
> 
> Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: D:\AI\AI\ComfyUI
> 
> Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: D:\AI\AI\ComfyUI
>

**Comment by if-ai** [comment]
You have to move the D:\AI\AI\ComfyUI\input\IF_AI\presets\agents IF_AI folder that comes with the repo to your input folder inside ComfyUI\input folder  you will see the IF_AI folder that contains a bunch of json files is the step 3 on the readme
