### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cardenluo** [if-ai/ComfyUI-IF_AI_tools#115]
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 110, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 55, in __init__
    self.stop_strings = self.load_presets(self.stop_file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 71, in load_presets
    with open(file_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\ComfyUI\\input\\IF_AI\\presets\\stop_strings.json'

**Comment by cardenluo** [comment]
![image](https://github.com/user-attachments/assets/3264608c-ea77-4336-92eb-d76bf8146d03)
how to update this "json"  ?

**Comment by cardenluo** [comment]
sorry , Copy it from the new download, and it's done.
