### ISSUE TITLE
Error during update by ComfyUI Manager

### ISSUE THREAD

**Issue by freshwind-bit** [if-ai/ComfyUI-IF_AI_tools#127]
When updating today from the August 14th version of all files by ComfyUI Manager, I got this error:

 Collecting nano-graphrag
   Downloading nano_graphrag-0.0.8.2-py3-none-any.whl.metadata (15 kB)
 Collecting future>=1.0.0 (from nano-graphrag)
   Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
    Collecting graspologic (from nano-graphrag)
   Downloading graspologic-3.4.1-py3-none-any.whl.metadata (5.8 kB)
 Collecting nano-vectordb (from nano-graphrag)
   Downloading nano_vectordb-0.0.4.3-py3-none-any.whl.metadata (3.7 kB)
 Collecting hnswlib (from nano-graphrag)
   Downloading hnswlib-0.8.0.tar.gz (36 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "E:\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "E:\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "E:\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "E:\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "E:\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
[!]       self.run_setup()
[!]     File "E:\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 6, in <module>
[!]   ModuleNotFoundError: No module named 'pybind11'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.

**Comment by PrometheusDante** [comment]
Got the same issue, failing to import ever since. Reinstalling didn't help.
