### ISSUE TITLE
UI be blocked when load the if_ai_tool workflow

### ISSUE THREAD

**Issue by chengyinqiao1976** [if-ai/ComfyUI-IF_AI_tools#128]
The UI blocked when load the workflow. I have update my comfyui to the newest version.

**Comment by K-O-N-B** [comment]
yes, can't cantrol the UI. Whole UI fail.

**Comment by 1456319** [comment]
same. totally breaks ui when loading the if chat prompt.

**Comment by Opeth66** [comment]
yes, same problem here

**Comment by Elgokoo** [comment]
same problem here

**Comment by 1456319** [comment]
ok, ill take a swing at it...

looks like the clicking issue can be stopped by going to settings >extensions and turning off the chatprompt extension. this wont delete the node from your workflow, but will not let you edit certain fields like embedding model, which the node will refuse to work without.

im going to try and narrow down the reason using inspect element on a working and broken instance & compare

ok yup, this populates in console on every click.

Uncaught error: TypeError: LiteGraph.getTime is not a functionUncaught error: TypeError: LiteGraph.getTime is not a function
    at LGraph.getNodeOnPos (label.js:140:39)
    at LGraphCanvas.processMouseDown (litegraph.es.js:4495:25)
    at LGraphCanvas.processMouseDown (changeTracker.ts:276:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:141:27)
    at LGraphCanvas.processMouseDown (rgthree.js:241:48)
    at LGraphCanvas.processMouseDown (app.ts:1235:40)
(anonymous) @ IFChatPromptNode.js:6


    at LGraph.getNodeOnPos (label.js:140:39)
    at LGraphCanvas.processMouseDown (litegraph.es.js:4495:25)
    at LGraphCanvas.processMouseDown (changeTracker.ts:276:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:141:27)
    at LGraphCanvas.processMouseDown (rgthree.js:241:48)
    at LGraphCanvas.processMouseDown (app.ts:1235:40)
(anonymous) @ IFChatPromptNode.js:6

label.js:140 
 Uncaught TypeError: LiteGraph.getTime is not a function
    at LGraph.getNodeOnPos (label.js:140:39)
    at LGraphCanvas.processMouseDown (litegraph.es.js:4495:25)
    at LGraphCanvas.processMouseDown (changeTracker.ts:276:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:141:27)
    at LGraphCanvas.processMouseDown (rgthree.js:241:48)
    at LGraphCanvas.processMouseDown (app.ts:1235:40)

and so...it's the rgthree extention which uses litegraph. i turned it off and its working so far.

cheers, great node btw.
