### ISSUE TITLE
help,Missing Node Types When loading the graph, the following node types were not found:IF_ChatPrompt

### ISSUE THREAD

**Issue by only1xiaobai** [if-ai/ComfyUI-IF_AI_tools#130]
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\AIGC\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\AIGC\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\AIGC\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 967, in INPUT_TYPES
    node = cls()
  File "D:\AIGC\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 383, in __init__
    self.assistants = self.load_presets(self.assistants_file)
  File "D:\AIGC\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 424, in load_presets
    presets = json.load(f)
  File "C:\Users\foxpa\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbe in position 5968: illegal multibyte sequence

Error loading presets from D:\AIGC\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IF_AI\presets\neg_prompts.json: 'gbk' codec can't decode byte 0x93 in position 198: illegal multibyte sequence

**Comment by isamu2025** [comment]
me too!

To see the GUI go to: http://127.0.0.1:8888
FETCH DATA from: G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "G:\comfyUI+AnimateDiff\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "G:\comfyUI+AnimateDiff\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 967, in INPUT_TYPES
    node = cls()
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 383, in __init__
    self.assistants = self.load_presets(self.assistants_file)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 424, in load_presets
    presets = json.load(f)
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbe in position 5968: illegal multibyte sequence


FileNotFoundError: [Errno 2] No such file or directory: 'G:\\comfyUI+AnimateDiff\\ComfyUI\\custom_nodes\\ComfyUI_IF_AI_tools\\__init__.py'

Cannot import G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI_IF_AI_tools module for custom nodes: [Errno 2] No such file or directory: 'G:\\comfyUI+AnimateDiff\\ComfyUI\\custom_nodes\\ComfyUI_IF_AI_tools\\__init__.py'
