### ISSUE TITLE
ImportError: cannot import name 'save_combo_settings' from 'ComfyUI-IF_AI_tools.utils'

### ISSUE THREAD

**Issue by pirona** [if-ai/ComfyUI-IF_AI_tools#137]
Full trace : 
```

Traceback (most recent call last):
  File "G:\IA\comfyui\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "G:\IA\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\__init__.py", line 10, in <module>
    from .IFImagePromptNode import IFImagePrompt
  File "G:\IA\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFImagePromptNode.py", line 14, in <module>
    from .utils import (
ImportError: cannot import name 'save_combo_settings' from 'ComfyUI-IF_AI_tools.utils' (G:\IA\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\utils.py)
```

This is happening in the following context : I updated python version from 3.10 to 3.12.6. 

This is my only issue : all my 221 other nodes are ok, as the rest of my setup.

What can I do ?

**Comment by ArthurReboulSalze** [comment]
Same here .

**Comment by Piscabo** [comment]
Also, have this error:
_Traceback (most recent call last):
  File "H:\ComfyUI\nodes.py", line 2089, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\__init__.py", line 10, in <module>
    from .IFImagePromptNode import IFImagePrompt
  File "H:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFImagePromptNode.py", line 14, in <module>
    from .utils import (
ImportError: cannot import name 'save_combo_settings' from 'ComfyUI-IF_AI_tools.utils' (H:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\utils.py)

Cannot import H:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools module for custom nodes: cannot import name 'save_combo_settings' from 'ComfyUI-IF_AI_tools.utils' (H:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\utils.py)_

**Comment by if-ai** [comment]
should be fixed now

**Comment by pirona** [comment]
Ok, on my side : thank you !
