### ISSUE TITLE
new version load fail

### ISSUE THREAD

**Issue by czcz1024** [if-ai/ComfyUI-IF_AI_tools#15]
Traceback (most recent call last):
  File "D:\ai\ComfyUI-aki-v1.1\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\__init__.py", line 10, in <module>
    from .IFDreamTalkNode import IFDreamTalk
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\IFDreamTalkNode.py", line 20, in <module>
    from .dreamtalk.core.utils import (
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\core\utils.py", line 13, in <module>
    from configs.default import get_cfg_defaults
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\configs\default.py", line 15, in <module>
    comfy_dir = find_comfy_dir(script_path)
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\configs\default.py", line 12, in find_comfy_dir
    return find_comfy_dir(parent_path)
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\configs\default.py", line 12, in find_comfy_dir
    return find_comfy_dir(parent_path)
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\configs\default.py", line 12, in find_comfy_dir
    return find_comfy_dir(parent_path)
  [Previous line repeated 4 more times]
  File "D:\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-IF_AI_tools\dreamtalk\configs\default.py", line 11, in find_comfy_dir
    raise Exception("ComfyUI directory not found")
Exception: ComfyUI directory not found

**Comment by if-ai** [comment]
is expecting ComfyUI-aki-v1.1 to be ComfyUI I am sorry I dont think I can change that in the code for now
