### ISSUE TITLE
An error occurred while retrieving information for the 'IF_ChatPrompt' node.

### ISSUE THREAD

**Issue by mr-bob-chang** [if-ai/ComfyUI-IF_AI_tools#67]
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 435, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 105, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 52, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 74, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\ComfyUI_windows_portable-b\\ComfyUI\\input\\IF_AI\\presets\\agents'

# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 435, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 105, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 52, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 74, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\ComfyUI_windows_portable-b\\ComfyUI\\input\\IF_AI\\presets\\agents'

# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
data_path:  E:\ComfyUI_windows_portable-b\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data

**Comment by if-ai** [comment]
You must move the IF_AI folder from ComfyUI/custom_nodes/ComfyUI-IF_AI_tools/ to the root input folder ComfyUI/input/IF_AI

In your case the agents should be present at
E:\ComfyUI_windows_portable-b\ComfyUI\input\IF_AI\presets\agents

**Comment by PrometheusDante** [comment]
I can confirm that moving the folder as described allowed the `IF Chat Prompt` node to load properly, as it showed as not found/red before that move.

**Comment by if-ai** [comment]
Thanks for reporting back, then I'll close the issue as solved I also added a new video if you have trouble [working with omost  ](https://www.youtube.com/watch?v=Tku2COSKR88)
