### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by magimyster** [if-ai/ComfyUI-IF_AI_tools#71]
after installing it, it gives me this error:

Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\__init__.py", line 9, in <module>
    from .IFChatPromptNode import IFChatPrompt
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 14, in <module>
    from .send_request import send_request
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\send_request.py", line 5, in <module>
    from .groq_api import send_groq_request
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\groq_api.py", line 1, in <module>
    from groq import Groq
ModuleNotFoundError: No module named 'groq'

**Comment by if-ai** [comment]
I forgot I was using Groq client instead of REST API please activate comfyui environment and `pip install groq` or if you have the manager click pip install and type `groq`

**Comment by magimyster** [comment]
> I forgot I was using Groq client instead of REST API please activate comfyui environment and `pip install groq` or if you have the manager click pip install and type `groq`

Okay, perfect... I'm not really an expert... thanks.

**Comment by magimyster** [comment]
ok now it's loaded thanks!
