### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.

### ISSUE THREAD

**Issue by gabrie** [if-ai/ComfyUI-IF_AI_tools#73]
I wish to try the latest IF running Omost through Ollama, aftyer updated IF Tools, met this error.

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\ComfyUI\server.py", line 434, in get_object_info
    out[x] = node_info(x)
  File "D:\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 105, in INPUT_TYPES
    node = cls()
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 52, in __init__
    self.agent_tools = self.load_agent_tools()
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 74, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\ComfyUI\\input\\IF_AI\\presets\\agents'

**Comment by gabrie** [comment]
start_local_llm error
BilboX LUTs path set to: D:\ComfyUI\custom_nodes\bilbox-comfyui\luts
Error loading assistants.json: AgentTool.__init__() got an unexpected keyword argument 'Cortana'
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "D:\ComfyUI\server.py", line 434, in get_object_info
    out[x] = node_info(x)
  File "D:\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 105, in INPUT_TYPES
    node = cls()
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
    self.assistants = self.load_presets(self.assistants_file)
  File "D:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 66, in load_presets
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI\\input\\IF_AI\\presets\\assistants.json'

**Comment by Laika92** [comment]
That was my error as well. Just move the IF_AI folder from ComfyUI/Custom_nodes /ComfyUI-IF_AI_tools to \ComfyUI_windows_portable\ComfyUI\input

**Comment by gabrie** [comment]
> That was my error as well. Just move the IF_AI folder from ComfyUI/Custom_nodes /ComfyUI-IF_AI_tools to \ComfyUI_windows_portable\ComfyUI\input

Thanks, same missing step 3, now solved!
