### ISSUE TITLE
IFChatPromptNode not found

### ISSUE THREAD

**Issue by GitAIUser** [if-ai/ComfyUI-IF_AI_tools#81]
2024-07-21 23:16:21.859 | ERROR    | logging:callHandlers:1706 - [ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
2024-07-21 23:16:21.860 | ERROR    | logging:callHandlers:1706 - Traceback (most recent call last):
  File "X:\StableDiff\ComfyUI\server.py", line 443, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI\server.py", line 420, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "X:\StableDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'X:\\StableDiff\\ComfyUI\\input\\IF_AI\\presets\\agents'

**Comment by if-ai** [comment]
You are missing step 3 from the readme. You have to manually move the IF_AI folder from ComfyUI/custom_nodes /ComfyUI-IF_AI_tools to the root of ComfyUI input folder like ComfyUI/input/IF_AI then it will be able to find the presets and other files it needs to start

**Comment by Unityisalreadybetaken** [comment]
> You are missing step 3 from the readme. You have to manually move the IF_AI folder from ComfyUI/custom_nodes /ComfyUI-IF_AI_tools to the root of ComfyUI input folder like ComfyUI/input/IF_AI then it will be able to find the presets and other files it needs to start您缺少自述文件中的第 3 步。您必须手动将IF_AI文件夹从 ComfyUI/custom_nodes /ComfyUI-IF_AI_tools 移动到 ComfyUI 输入文件夹的根目录，如 ComfyUI/input/IF_AI然后它将能够找到启动所需的预设和其他文件

it do work, thanks, but my bad to ignore the READ_ME file.

**Comment by John-OK** [comment]
> You are missing step 3 from the readme. You have to manually move the IF_AI folder from ComfyUI/custom_nodes /ComfyUI-IF_AI_tools to the root of ComfyUI input folder like ComfyUI/input/IF_AI then it will be able to find the presets and other files it needs to start

I think Steps 3 and 4 need to be switched as, currently, the instructions state to move the folder before the repo is cloned, and the folder will not exist until the repo is cloned.
