### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by oooobird2023** [if-ai/ComfyUI-IF_AI_tools#82]
I have downloaded the requirements and tried to download them manually or through the manager. The environment and mobile IF AI folder have been installed, but errors still occur。thank you！

![11](https://github.com/user-attachments/assets/1f3dc11c-3932-4ee0-a494-090e3f35784a)
![22](https://github.com/user-attachments/assets/02de0642-8d47-437e-b1cc-05a303394306)

Cannot import F:\ComfyUI2\ComfyUI\custom_nodes\ComfyUI-IDM-VTON module for custom nodes: No module named 'diffusers.models.dual_transformer_2d'
Traceback (most recent call last):
  File "F:\ComfyUI2\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI2\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\__init__.py", line 9, in <module>
    from .IFChatPromptNode import IFChatPrompt
  File "F:\ComfyUI2\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 12, in <module>
    from .get_api import get_api_key
  File "F:\ComfyUI2\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\get_api.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Cannot import F:\ComfyUI2\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools module for custom nodes: No module named 'dotenv'
Unable to import guidedFilter, make sure you have only opencv-contrib-python or run the import_error_install.bat script

**Comment by if-ai** [comment]
activate your comfy environment and `pip install python-dotenv`

**Comment by tatookan** [comment]
How do I activate a virtual environment
