### ISSUE TITLE
No attribute  "Keys"

### ISSUE THREAD

**Issue by algisju** [if-ai/ComfyUI-IF_AI_tools#85]
After trying to install IF_AI_Tools, I get this error :

[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "C:\code\comfyui\ComfyUI\server.py", line 443, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\code\comfyui\ComfyUI\server.py", line 420, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\comfyui\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 128, in INPUT_TYPES
    "stop_string": ([name for name in node.stop_strings.keys()], {}),
                                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'

Please let me know what did I miss and orient me for a solution,

Thanks

**Comment by if-ai** [comment]
probably need to move the IF_AI folder to the input folder inside the root of comfy like in step 3 on the readme installation instructions
